Repository FromDoppler/hello-microservice, pull requests merged in 2021-04, with the labels that each got.

#1 DE-135 - base project
  .config/dotnet-tools.json
  .dockerignore
  .doppler-ci
  .editorconfig
  .gitattributes
  .gitignore
  .prettierignore
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  Dockerfile
  Doppler.HelloMicroservice.Test/Doppler.HelloMicroservice.Test.csproj
  Doppler.HelloMicroservice.Test/UnitTest1.cs
  Doppler.HelloMicroservice/Controllers/WeatherForecastController.cs
  Doppler.HelloMicroservice/Dockerfile
  Doppler.HelloMicroservice/Doppler.HelloMicroservice.csproj
  Doppler.HelloMicroservice/Program.cs
  Doppler.HelloMicroservice/Properties/launchSettings.json
  Doppler.HelloMicroservice/Startup.cs
  Doppler.HelloMicroservice/WeatherForecast.cs
  Doppler.HelloMicroservice/appsettings.Development.json
  Doppler.HelloMicroservice/appsettings.json
  Doppler.HelloMicroservice/wwwroot/favicon.ico
  Doppler.HelloMicroservice/wwwroot/robots.txt
  HelloMicroservice.sln
  Jenkinsfile
  README.md
  build-n-publish.sh
  demo.http
  package.json
  verify-w-docker.sh
  yarn.lock
Labels: size/XXL

#8 DE-135 - Fix prettier
  .dockerignore
  .prettierignore
  README.md
Labels: size/M

#9 DE-135 - Create Dependabot config file
  .github/dependabot.yml
Labels: size/M

#2 test: add an example of self-hosting integration test
  Doppler.HelloMicroservice.Test/Doppler.HelloMicroservice.Test.csproj
  Doppler.HelloMicroservice.Test/IntegrationTest1.cs
  README.md
Labels: size/M

#10 chore: add .gitlint to .prettierignore
  .prettierignore
Labels: size/XS

#11 DE-135 - Gitlint fine tune
  .gitlint
Labels: size/XS

#12 DE-135 - Doppler security
  .prettierignore
  Doppler.HelloMicroservice.Test/AuthorizationTest.cs
  Doppler.HelloMicroservice.Test/HttpResponseMessageExtensions.cs
  Doppler.HelloMicroservice/Controllers/HelloController.cs
  Doppler.HelloMicroservice/Doppler.HelloMicroservice.csproj
  Doppler.HelloMicroservice/DopplerSecurity/ConfigureDopplerSecurityOptions.cs
  Doppler.HelloMicroservice/DopplerSecurity/DopplerAuthorizationRequirement.cs
  Doppler.HelloMicroservice/DopplerSecurity/DopplerSecurityDefaults.cs
  Doppler.HelloMicroservice/DopplerSecurity/DopplerSecurityOptions.cs
  Doppler.HelloMicroservice/DopplerSecurity/DopplerSecurityServiceCollectionExtensions.cs
  Doppler.HelloMicroservice/DopplerSecurity/IsOwnResourceAuthorizationHandler.cs
  Doppler.HelloMicroservice/DopplerSecurity/IsSuperUserAuthorizationHandler.cs
  Doppler.HelloMicroservice/DopplerSecurity/Policies.cs
  Doppler.HelloMicroservice/Startup.cs
  Doppler.HelloMicroservice/appsettings.Development.json
  Doppler.HelloMicroservice/appsettings.json
  Doppler.HelloMicroservice/private-keys-dev/README.md
  Doppler.HelloMicroservice/private-keys-dev/dev.priv.key
  Doppler.HelloMicroservice/private-keys-dev/dev.priv.xml
  Doppler.HelloMicroservice/public-keys-dev/dev.pub.key
  Doppler.HelloMicroservice/public-keys-dev/dev.pub.xml
  Doppler.HelloMicroservice/public-keys/README.md
  demo.http
Labels: size/XL

#14 DE-135 - Service provider validation
  Doppler.HelloMicroservice/Controllers/WeatherForecastController.cs
  Doppler.HelloMicroservice/Program.cs
  Doppler.HelloMicroservice/Startup.cs
  Doppler.HelloMicroservice/Weather/DataService.cs
  Doppler.HelloMicroservice/Weather/WeatherForecast.cs
  Doppler.HelloMicroservice/Weather/WeatherForecastService.cs
Labels: size/M

#13 DD-356 Add logging
  Doppler.HelloMicroservice/Doppler.HelloMicroservice.csproj
  Doppler.HelloMicroservice/Logging/LogglySetup.cs
  Doppler.HelloMicroservice/Logging/SerilogSetup.cs
  Doppler.HelloMicroservice/Program.cs
  Doppler.HelloMicroservice/appsettings.Development.json
  Doppler.HelloMicroservice/appsettings.json
Labels: size/L

#16 fix: allow authorize with api key in swagger
  Doppler.HelloMicroservice/Startup.cs
Labels: size/S
